### ISSUE TITLE
Bug: unable to npm install

### ISSUE THREAD

**Issue by OmriOn** [Solar-Tweaks/SolarStats#7]
When entering npm install, all that shows up is: "npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\XXXX\Documents\SolarStats\node_modules\.staging\javascript-obfuscator-f63bd6ad\typings'"

**Comment by Steviegt6** [comment]
I can't be asked to figure out GitHub NPM package authentication (which is the issue here, FYI), but you can run `npm i https://github.com/Solar-Tweaks/minecraft-protocol-lunarclient` to install `minecraft-protocol-lunarclient` using `git clone`. Run `npm run build` afterward and it'll build fine.

If -- for some reason -- this doesn't work, please delete the `.npmrc` file at your `$HOME` directory (most likely `C:\Users\You\` on Windows), delete the `package-lock.json` file in your `SolarStats` folder, and run `npx vsts-npm-auth -config .npmrc` in a command line that has the `SolarStats` folder open.
